openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about users.
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-contacts-app.onrender.com
paths:
  /contacts:
    post:
      $ref: ../swagger/paths/contacts/post.yaml
    get:
      $ref: ../swagger/paths/contacts/get.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
